Monitoring 1
Otus-DevOps-2017-11/asomir_microservices pull request #7
Opened 2018-03-17 16:22 UTC by asomir

# Homework 21

## Введение в мониторинг. Системы мониторинга.

### Подготовка окружения

##### 1. Создадим правило для файерволла Прометеуса и Пумы соответственно:

```bash
$ gcloud compute firewall-rules create prometheus-default --allow tcp:9090

$ gcloud compute firewall-rules create puma-default --allow tcp:9292

```

##### 2. Создадим Docker хост в GCE и настроим локальное окружение на работу с ним

> export GOOGLE_PROJECT=docker-194414

##### 3. Создаём докер хост, с которым мы и будем работать

```bash
# create docker host
docker-machine create --driver google \
    --google-machine-image https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts \
    --google-machine-type n1-standard-1 \
    vm1
```
##### 4. Подключаемся к докер машине
```bash
# configure local env
eval $(docker-machine env vm1)

```

### Запуск Prometheus

##### 5. Запускаем Прометея внутри докер контейнера. Коварно воспользуемся готовым образом:

```bash
$ docker run --rm -p 9090:9090 -d --name prometheus prom/prometheus:v2.1.0
```
проверяем ШуЗы Прометея

```bash
docker-machine ip vm1
```

и идём по полученному ШуЗу http://35.225.212.35:9090/graph

### Targets

##### Памятка:

Targets (цели) - представляют собой системы или процессы, за
которыми следит Prometheus. Помним, что Prometheus является
pull системой, поэтому он постоянно делает HTTP запросы на
имеющиеся у него адреса (endpoints). Посмотрим текущий список
целей

В Targets сейчас мы видим только сам Prometheus. У каждой
цели есть свой список адресов (endpoints), по которым
следует обращаться для получения информации.

В веб интерфейсе мы можем видеть состояние каждого
endpoint-а (up); лейбл (instance="someURL"), который
Prometheus автоматически добавляет к каждой метрике,
получаемой с данного endpoint-а; а также время,
прошедшее с момента последней операции сбора
информации с endpoint-а.

Также здесь отображаются ошибки при их наличии и можно
отфильтровать только неживые таргеты.

Мы можем открыть страницу в веб браузере по данному HTTP
пути (host:port/metrics), чтобы посмотреть, как выглядит та
информация, которую собирает Prometheus.

##### Остановим Прометея

```bash
docker stop prometheus
```

### Создание Docker образа

##### 6. Создаём докер файл monitoring/prometheus/Dockerfile, который копирует файл конфигурации с нашей машины внутрь контейнера:

```docker
FROM prom/prometheus:v2.1.0
ADD prometheus.yml /etc/prometheus/
```

##### 7. В директории monitoring/prometheus создали файл prometheus.yml

```yamlex
global:
  scrape_interval: '5s' # частота сбора метрик 

scrape_configs: # Эндпойнты - группы метрик, собирающих одинаковые данные
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090' # адрес, откуда чо собираем

  - job_name: 'ui'
    static_configs:
      - targets:
        - 'ui:9292'

  - job_name: 'comment'
    static_configs:
      - targets:
        - 'comment:9292'
```

##### 8. В директории prometheus собираем Docker образ:

```bash
$ export USER_NAME=asomir
$ docker build -t $USER_NAME/prometheus .
```

### Образы микросервисов

##### 9. Сборку образов производим при помощи скриптов docker_build.sh, которые есть в директории каждого сервиса. С его помощью мы добавим информацию из Git в наш healthcheck.

Запустиим сразу все из корня репы и пойдём пить кофе

```bash
for i in ui post-py comment; do cd src/$i; bash
docker_build.sh; cd -; done
```

##### 10. Определиv в вашем docker/docker-compose.yml файле новый сервис.

```yamlex
version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    container_name: ui
    image: ${USERNAME}/ui:latest
    ports:
      - ${APP_PORT}:9292/tcp
    networks:
      - front_net
  post:
    container_name: post-py
    image: ${USERNAME}/post:latest
    networks:
      - front_net
      - back_net
  comment:
    container_name: comment
    image: ${USERNAME}/comment:latest
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
```
Запускаем docker-compose up -d и проверяем работоспособность 

http://35.225.212.35:9090/graph
http://35.225.212.35:9292/

### Мониторинг состояния микросервисов

Проверяем состояние наших эндпойнтов: comment, ui, prometheus

http://35.225.212.35:9090/targets

### Healthchecks

#### Памятка 

Healthcheck-и представляют собой проверки того, что
наш сервис здоров и работает в ожидаемом режиме. В
нашем случае healthcheck выполняется внутри кода
микросервиса и выполняет проверку того, что все
сервисы, от которых зависит его работа, ему доступны.
Если требуемые для его работы сервисы здоровы, то
healthcheck проверка возвращает status = 1, что
соответсвует тому, что сам сервис здоров.
Если один из нужных ему сервисов нездоров или
недоступен, то проверка вернет status = 0.

#### Состояние сервиса UI

Выполнили поиск в веб-интерфейсе прометея ui_health, однако он ничего не нашёл. Зашёл на сайт реддит и сделал пост, - после этого Прометей нашёл метрику

ui_health{branch="monitoring-1",commit_hash="d3d08a6",instance="ui:9292",job="ui",version="0.0.1"}

Где показано название ветки в гите, коммите и лейблах

Перешли в графическое отображение, увидели единицу, и она прекрасна. Остановили сервис post.

> docker-compose stop post

график упал в ноль. И это ужасно. Поплачем друзья, ведь сервис нездоров.

Зашёл посмотреть на ui_health_comment_availability и вижу прекрасную единицу.

Зашёл глянуть на ui_health_post_availability и обожечки! Что я вижу! Полный ноль! Сервис мёртв! Что же делать?!

Поднимем же сервис пост, вставай, дружочек:

> docker-compose start post

ui_health_post_availability{branch="monitoring-1",commit_hash="d3d08a6",instance="ui:9292",job="ui",version="0.0.1"}

Жив и здоров, мы пришили ему ножки! 

## Exporters

#### Памятка 

• Программа, которая делает метрики доступными
для сбора Prometheus 

• Дает возможность конвертировать метрики в
нужный для Prometheus формат 

• Используется когда нельзя поменять код
приложения 

• Примеры: PostgreSQL, RabbitMQ, Nginx, Node
exporter, cAdvisor 

### Node exporter

##### Определим еще один сервис в docker/docker-compose.yml файле.

```yamlex
services:

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
```

##### Добавим слежение за новым сервисом в Прометей

```yamlex
  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'
```
##### Пересоздадим докер для Прометея

monitoring/prometheus 

```bash
$ docker build -t $USER_NAME/prometheus .
```

##### Пересоздадим наши сервисы

```bash
$ docker-compose down
$ docker-compose up -d
```
В списке эндпойнтов появился ещё один сервис node

##### Получим информацию об использовании CPU 

Зайдем на хост: 

> docker-machine ssh vm1 

Добавим нагрузки: 

yes > /dev/null

Посмотрим на весёлые графики

##### Запушили собранные образы на DockerHub:
$ docker login
Login Succeeded

docker push $USER_NAME/ui
docker push $USER_NAME/comment
docker push $USER_NAME/post
docker push $USER_NAME/prometheus

Удалили виртуалку:
$ docker-machine rm vm1

## Ссылка на мой репозиторий: 

https://hub.docker.com/r/asomir/

2018-03-21 07:03 UTC, Nklya commented
Добавлять нужно было ревьюверов, а не assignee

2018-03-21 07:13 UTC, Nklya requested changes
Привет.

Александр, все выглядит относительно ок.

Нужно вычистить build_info.txt, .env и  добавить .env.example

2018-03-21 07:13 UTC, Nklya commented on src/ui/build_info.txt
> +d3d08a6
build_info.txt нужно добавить в .gitignore и вычистить

2018-03-21 07:13 UTC, Nklya commented on src/post-py/build_info.txt
> +d3d08a6
build_info.txt нужно добавить в .gitignore и вычистить

2018-03-21 07:13 UTC, Nklya commented on docker/.env
> +VERSION_MONGO=3.2
.env нужно добавить в .gitignore и вычистить.
В репозитории должен быть .env.example

2018-03-24 15:34 UTC, asomir commented
Прошу прощения, Коля. Вроде, всё поправил :) git rm --cached `git ls-files -i -X .gitignore`

2018-03-24 15:38 UTC, Nklya approved these changes
Привет.

Александр, теперь все ок 👍

2018-03-24 15:38 UTC, Nklya commented on docker/reddit.env
> +VERSION_MONGO=3.2
А этот env зачем?

2018-03-25 10:14 UTC, merged

2018-03-25 10:15 UTC, asomir commented on docker/reddit.env
> +VERSION_MONGO=3.2
Фиг знает, мне Андрей сказал его сделать. Мол, оно же должно как-то называться